### ISSUE TITLE
If WP Staging debug mode is active write php errors into wp staging logs

### ISSUE THREAD

**Issue by Koks-A-Cola** [WP-Staging/wp-staging#144]
See #285 on Pro

**Comment by rene-hermenau** [comment]
The title seems to be incorrect. It adds the debug.log to reports but does not write any additional errors or activate the debug.log. It's probably not that easy to activate the debug.log by using a wp staging setting as it would require overwriting WP_DEBUG constant in wp-config.php?

**Comment by Koks-A-Cola** [comment]
I just copied the title from the Pro version repository. Functionality will be the same as there.
