### ISSUE TITLE
Step 4 of staging (Copy Files) doesn't work

### ISSUE THREAD

**Issue by TymurGubayev** [wp-staging/wp-staging#176]
Clicking "create new" I get "Processing Complete" and a "Congratulations WP Staging successfully created a staging site in a sub-directory of your main site accessable from: http://myhost/staging" message, but actually the site is completely empty.

Looking into the log, it goes wrong from following

> [INFO]-[2020/11/18 10:00:07] Copying files...
> [WARNING]-[2020/11/18 10:00:07] File doesn't exist /usr/share/wordpress//var/www/html/wordpress/wp-content/languages/sw.mo
> [WARNING]-[2020/11/18 10:00:07] File doesn't exist /usr/share/wordpress//var/www/html/wordpress/wp-content/languages/admin-sr_RS.mo

And so on for the next 5250 files.

Notice how the file paths are a concatenation of `/usr/share/wordpress/` and an actual file path like `/var/www/html/wordpress/wp-content/languages/sw.mo`.

After those 5250 processed it proceeds without warnings up until 6950 processed files when the following happens.

> [INFO]-[2020/11/18 10:00:41] Total 6950 files processed
> [WARNING]-[2020/11/18 10:00:41] File doesn't exist /usr/share/wordpress/
> [INFO]-[2020/11/18 10:00:41] Copying files finished
> [INFO]-[2020/11/18 10:00:41] DB Data Step0: Copy wp-config.php file
> [INFO]-[2020/11/18 10:00:41] DB Data Step0: Can not find DB_PASSWORD in wp-config.php
> [INFO]-[2020/11/18 10:00:41] DB Data Step0: Can not find /usr/share/wp-config.php
> [INFO]-[2020/11/18 10:00:41] DB Data Step0: Copy default wp-config.php file from source /usr/share/wordpress/wp-content/plugins/wp-staging/Backend/helpers/wp-config.php to /usr/share/wordpress/staging/wp-config.php

But my `wp-config.php` is at `/usr/share/wordpress/wp-config.php`, not `/usr/share/wp-config.php`, and of course `/usr/share/wordpress/` exists (but it is a directory, not a file).

**Comment by rene-hermenau** [comment]
Hi,

Please send me the system information from wp staging > tools > system info to the mail address support [at] wp-staging.com and to me in person.

I need some more details about your website setup. If you can provide me with login credentials that would be even better.

Cheers
René

**Comment by TymurGubayev** [comment]
Hi @rene-hermenau,

I'm sorry I'm unable to find your personal e-mail address, I've sent it to the support -- it got Ticket ID: 20187.

It might be possible to provide you the login credentials, but I can't decide this alone -- should it prove impossible to diagnose the issue otherwise we will return to this.

Regards,
 Timur
